import "./globals.css";
import localFont from "next/font/local";

const europeanTeletext = localFont({
  src: "./EuropeanTeletext.ttf",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={europeanTeletext.className}>
        <main className="grid min-h-full place-items-center bg-black text-white lg:bg-blue-900">
          <article className="mx-auto bg-black px-16 py-8">{children}</article>
        </main>
      </body>
    </html>
  );
}
